apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jy7iw9t6e-nodejs
  janus-idp.io/tekton: jy7iw9t6e-nodejs
  backstage.io/kubernetes-id: jy7iw9t6e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jy7iw9t6e-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
